config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :lists do
    collection do
      get :due_this_week
    end
    resources :tasks do
      collection do
        get :completed_index
      end
      member do
        post :complete
      end
      resources :categories
    end
  end
  root "lists#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :task
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :task
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  validates :name, presence: true, uniqueness: true
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  has_one :link
  accepts_nested_attributes_for :link

  has_and_belongs_to_many :category

  validates :description, :due_at, presence: true

  scope :incompleted_tasks, -> { where(completed_at: nil) }
  scope :completed_tasks, -> { where.not(completed_at: nil ) }
  scope :overdue, -> { where( 'due_at > ?', Time.now ) }
  scope :pending, -> { where( 'due_at < ?', Time.now) }

  def self.created_since(since)
    where( 'created_at > ?', since )
  end

  def self.due_within(within)
    where( 'due_at < ?', within )
  end

  def self.priority_higher_than(min_priority)
    where( 'priority > ?', min_priority )
  end

  def complete!
    self.completed_at = Time.now
    self.save!
  end

  def overdue?
    due_at.present? && due_at < Time.now
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
  has_many :tasks, through: :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, except: [ :index, :new, :create, :due_this_week]
  before_action :find_user

  def index
    @lists = @user.lists
  end

  def new
    @list = @user.lists.new
  end

  def show
    redirect_to list_tasks_url(@list)
  end

  def create
    @list = @user.lists.new(list_params)
    if @list.save
      redirect_to lists_url, notice: "Created #{@list.name}"
    else
      render :new
    end
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to lists_path, notice: "List updated"
    else
      render :edit
    end
  end

  def due_this_week
    @tasks = @user.tasks.due_within(1.week.from_now)
  end

  def destroy
    @list.destroy
    redirect_to lists_url
  end

  private
    def list_params
      params.require(:list).permit(:name)
    end

    def find_list
      @list = List.find(params[:id])
    end

    def find_user
      @user = current_user
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_list
  before_action :find_task, only: [ :destroy, :complete, :edit, :update ]
  before_action :find_tasks, only: [ :index, :create, :completed_index, :complete_me ]

  def index
    @tasks = @tasks.incompleted_tasks.decorate
    @task = Task.new
    @task.build_link
  end

  def edit
    @task.build_link unless @task.link.present?
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      @list.tasks << @task
      render partial: @task
    else
      render text: @task.errors.full_messages.join(", "), status: 500
    end
  end

  def update
    if @task.update_attributes(task_params)
      redirect_to list_tasks_path(@list), notice: "Task updated"
    else
      render :edit
    end
  end

  def complete
    @task.complete!
    redirect_to list_tasks_path(@list), notice: "#{@task.description} completed"
  end

  def completed_index
    @tasks = @tasks.completed_tasks
  end

  def destroy
    @task.destroy
    redirect_to list_tasks_url(@list), notice: 'Deleted Task'
  end

  private
    def find_list
      @list = List.find(params[:list_id])
    end

    def find_task
      @task = @list.tasks.find(params[:id])
    end

    def find_tasks
      @tasks = @list.tasks
    end

    def task_params
      params.require(:task).permit(
        :description,
        :due_at,
        :priority,
        :completed,
        :complete,
        category_ids: [],
        link_attributes: [:url]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_greeting
    if current_user.sign_in_count == 1
      "Hi #{current_user.first_name}. Welcome to Check!"
    else
      "Welcome back, #{current_user.first_name}!"
    end
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Check</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <!-- Fixed navbar -->
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/"> CHECK </a>
      </div>
      <div>
        <ul class="nav navbar-nav navbar-right">
          <li class="nav navbar-text"> <%= user_greeting if user_signed_in? %> </li>
          <li class="nav navbar-nav"> <%= link_to "Signout", destroy_user_session_path, method: :delete if user_signed_in? %> </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Begin page content -->
  <div class="top-page-margin">
    <div class="container">
      <div>
        <% if flash[:notice] %>
          <div id="myAlert" class="alert alert-warning fade" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= flash[:notice] %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>

  <footer class="footer">
    <div class="container">
      <p class="text-muted"></p>
    </div>
  </footer>


  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="./Sticky Footer Navbar Template for Bootstrap_files/jquery.min.js"></script>
  <script src="./Sticky Footer Navbar Template for Bootstrap_files/bootstrap.min.js"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="./Sticky Footer Navbar Template for Bootstrap_files/ie10-viewport-bug-workaround.js"></script>

</body>
</html>

app/views/lists/_list.html.erb
<tr>
  <td>
    <%=  %>
  </td>
</tr>

app/views/lists/due_this_week.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Lists", lists_path %> </li>
  <li class="active">Tasks due this week</li>
</ol>

<div class="row">
  <div class="page-header">
    <h3>Tasks due this week</h3>
  </div>
</div>

<div class="row">

  <table class="table table-striped">
    <thead>
      <tr>
        <td>Name</td>
        <td></td>
      </tr>
    </thead>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/lists/edit.html.erb
<div class="container">

  <div class="row">
  </div>

  <div class="row">
    <div class="page-header">
      <h3>Edit list: <%= @list.name %></h3>
    </div>

    <div class="col-sm-8 col-md-6 col-lg-5">
      <%= simple_form_for @list, html: { class: 'form-horizontal' } do |form| %>
        <%= form.input :name %>
        <%= form.submit class: 'btn btn-success pull-left' %>
      <% end %>
    <%= link_to "Cancel", lists_path, class: 'btn btn-warning pull-right' %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-sm-4 column-lists">

      <ul class="list-group"> <%= %> </ul>

    </div>
    <div class="col-xs-6 col-sm-4 column-tasks">

    </div>
    <div class="col-xs-6 col-sm-4 column-extras">


    </div>



      <h3>Lists</h3>
    </div>
  </div>

  <div class="row">
    <table class="table table-striped col-sm-8">
      <thead>
        <tr>
          <td>Name</td>
          <td>Actions</td>
        </tr>
      </thead>
      <% @lists.each do |list| %>
        <tr>
          <td>
            <%= link_to(list.name, list_path(list)) %>
          </td>
          <td>

            <!-- Split button -->
            <div class="btn-group">
              <%= link_to "Edit", edit_list_path(list), class: 'btn btn-danger btn-xs' %>
              <button type="button" class="btn btn-danger btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to "Delete", list_path(list), method: :delete, data: { confirm: 'Are you sure?' } %>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="row text-center">
    <%= link_to "New List", new_list_path, class: 'btn btn-default' %>
    <%= link_to "Show tasks due this week", due_this_week_lists_path, class: 'btn btn-default btn-md' %>
  </div>

</div>

app/views/lists/new.html.erb
<div class="container">

  <div class="row">
  </div>

  <div class="row">
    <div class="page-header">
      <h3>Create new List</h3>
    </div>

    <div class="col-sm-8 col-md-6 col-lg-5">
      <%= simple_form_for @list, html: { class: 'form-horizontal' } do |form| %>
        <%= form.input :name, class: 'form-control' %>
        <%= form.submit class: 'btn btn-success' %>
      <% end %>
    <%= link_to "Cancel", lists_path, class: 'btn btn-warning' %>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-sm-8">
    <%= simple_form_for [@list, @task], html: { class: 'form-horizontal' } do |form| %>
      <%= form.input :description %>
      <%= form.input :priority %>
      <div class="form-group">
        <%= form.label :due_at, class: "control-label" %>
        <%= form.date_field :due_at, class: "form-control" %>
      </div>
      <%= form.association :category, as: :check_boxes, collection: Category.all %>
      <%= form.simple_fields_for :link do |link_field| %>
        <%= link_field.input :url %>
      <% end %>
      <%= form.button :submit, class: 'btn btn-success' %>
    <% end %>
  </br>
    <%= link_to "Cancel", list_path(@list), class: 'btn btn-danger' %>
  </div>
</div>

app/views/tasks/_task.html.erb
<tr>
  <td><%= link_to task.description, edit_list_task_path(@list, task) %></td>
  <td> <%= task.due_at %> </td>
  <td>
    <% task.category.each do |cat| %>
       <div class="label text-center <%= cycle('label-success', 'label-info', 'label-warning', 'label-danger') %>">
      <%= cat.name  %>
      </div>
    <% end %>
  </td>
  <td>
    <%= link_to "Delete", list_task_path(@list, task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-xs' %>
    <%= link_to "Complete", complete_list_task_path(@list, task), method: :post, class: 'btn btn-default btn-xs' %>
  </td>
</tr>

app/views/tasks/completed_index.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Lists", lists_path %></li>
  <li class="active"><%= link_to @list.name, list_path(@list) %></li>
  <li class="active">Completed tasks</li>
</ol>

<div class="row">
  <div class="page-header">
    <h3><%= @list.name %>: completed </h3>
  </div>
</div>

<div class="row">

  <table class="table table-striped">
    <thead>
      <tr>
        <td>Name</td>
        <td></td>
      </tr>
    </thead>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td>
          <%= link_to "Delete", list_task_path(@list, task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/tasks/edit.html.erb
<div class="container">

  <ol class="breadcrumb">
    <li><%= link_to "Lists", lists_path %></li>
    <li class="active"><%= link_to @list.name, list_path(@list) %></li>
  </ol>

  <div class="row">
    <div class="page-header">
      <h3> Edit Task </h3>
    </div>
  </div>

  <%= render partial: 'form'  %>

</div>

app/views/tasks/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Lists", lists_path %></li>
  <li class="active"><%= @list.name %></li>
</ol>

<div class="container">

  <div class="row">
    <div class="page-header">
      <h3><%= @list.name %></h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="new-task-form">
        <%= simple_form_for [@list, @task], html: {class: 'form-inline' }, remote: true do |form| %>
          <%= form.input :description,
            placeholder: 'Add a Task',
            label: false,
            wrapper: false,
            input_html: { class: "input-task" } %>
          <%= form.date_field :due_at, class: "form-control input-date" %>
          <%= form.submit class: "btn btn-success pull-right" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <table class="table table-striped">
        <thead>
          <tr>
            <td>Name</td>
            <td>Due at</td>
            <td>Categories</td>
            <td>Actions</td>
          </tr>
        </thead>
        <tbody id="tasks">
          <%= render @tasks %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <%= link_to "Show completed tasks", completed_index_list_tasks_path(@list), class: 'btn btn-default btn-md' %>
    </div>
  </div>

</div>